import { ExtractionResult, PatternToken } from '../../types';

export function generateAuditReport(
  result: ExtractionResult,
  workbookName: string,
  sheetName: string,
  mediaColumns: string[],
  tokens: PatternToken[]
): string {
  const now = new Date().toISOString();
  const patternDesc = tokens.map(t => {
    if (t.type === 'column') return `[${t.value}]`;
    if (t.type === 'text') return t.value;
    if (t.type === 'mediaType') return `[Media Type]`;
    if (t.type === 'rowNumber') return `[Row Number]`;
    if (t.type === 'originalName') return `[Original Name]`;
    return `[${t.type}]`;
  }).join('');

  return `# SECURE MEDIA EXTRACTION AUDIT REPORT

**Processed At**: ${now}
**Workbook File**: ${workbookName}
**Target Worksheet**: ${sheetName}
**Security Model**: 100% Client-Side Local Processing (No Cloud Upload)

---

## 1. Execution Summary

- **Total Media Objects Discovered**: ${result.totalFound}
- **Successfully Exported**: ${result.exportedCount}
- **Skipped Rows**: ${result.skippedCount}
- **Unmapped Media**: ${result.unmappedCount}
- **Duplicate Collision Renames**: ${result.duplicateCount}
- **Errors**: ${result.errorCount}

---

## 2. Configuration Settings

- **Selected Media Columns**: ${mediaColumns.join(', ')}
- **Filename Pattern Structure**: \`${patternDesc}\`
- **Output Archive**: \`${result.zipFilename}\`

---

## 3. Detailed File Log

| Item | Source Cell | Target Folder | Generated Filename | Extraction Status |
|---|---|---|---|---|
${result.items.map((item, idx) => {
  const i = item.item;
  const statusStr = i.status === 'ready' ? 'SUCCESS' : i.status.toUpperCase();
  return `| ${idx + 1} | ${i.cellRef} | ${item.folderPath} | ${item.finalFilename} | ${statusStr} |`;
}).join('\n')}

---

*Report automatically generated by Secure Excel Media Extractor. Confidential local processing.*
`;
}
